# -*- coding: utf-8 -*-
"""01_Hello_Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqdVZq9iIwfKTVOzE4BSNo-35FZ8C5uc
"""

!pip install -qU langchain-google-genai

from langchain_google_genai import ChatGoogleGenerativeAI
from google.colab import userdata
api_key = userdata.get('Gem_key')

model = ChatGoogleGenerativeAI(api_key=api_key, model=('gemini-2.0-flash-exp'))

from langchain import PromptTemplate, LLMChain

prompt_template = PromptTemplate(
    input_variables=["question"],
    template="""You are an expert in the field of Forex only. Answer only those questions that are related to your area of expertise; i.e., FOREX.

    **If the question is not directly related to Forex, politely refuse to answer by saying "I'm sorry, I can't answer that. I'm best at questions about Forex."**

    Now answer the following question if it is directly related to Forex: {question}"""
)

chain = LLMChain(llm=model, prompt=prompt_template)

# Run the chain with a sample question
question = "How long will it take to learn AI fully for a newbie?"
response = chain.run({"question": question})

print("Answer:", response)

# Run the chain with a sample question
question = "Is Forex Trading here to stay for life?"
response = chain.run({"question": question})

print("Answer:", response)

# Run the chain with a sample question
question = "How to drive a car?"
response = chain.run({"question": question})

print("Answer:", response)